/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki1.CombatResult;
import napakalaki1.Monster;
import napakalaki1.Napakalaki;
import napakalaki1.Player;

/**
 *
 * @author TOSHIBA
 */
public class NapakalakiView extends javax.swing.JFrame {
    
    Player Player;
    MonsterView monster;
    Napakalaki napakalakiModel= Napakalaki.getInstance();
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
        monsterView1.setVisible(false);
        nextTurn.setEnabled(false);
        combat.setEnabled(false);
    }
    public void setNapakalaki(Napakalaki n){
        napakalakiModel=n;
        monsterView1.setMonster(napakalakiModel.getCurrentMonster());
        playerView21.setPlayer(napakalakiModel.getCurrentPlayer());
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  //  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monsterView1 = new GUI.MonsterView();
        playerView21 = new GUI.PlayerView2();
        jLabel1 = new javax.swing.JLabel();
        nextTurn = new javax.swing.JButton();
        combat = new javax.swing.JButton();
        meetMonster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        monsterView1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(monsterView1);
        monsterView1.setBounds(10, 323, 829, 203);

        playerView21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        getContentPane().add(playerView21);
        playerView21.setBounds(10, 67, 1120, 250);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 55)); // NOI18N
        jLabel1.setText("NAPAKALAKI");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 11, 567, 45);

        nextTurn.setText("Siguiente turno");
        nextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnActionPerformed(evt);
            }
        });
        getContentPane().add(nextTurn);
        nextTurn.setBounds(849, 466, 281, 60);

        combat.setText("Combatir");
        combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatActionPerformed(evt);
            }
        });
        getContentPane().add(combat);
        combat.setBounds(849, 395, 281, 60);

        meetMonster.setText("Conocer al monstruo");
        meetMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetMonsterActionPerformed(evt);
            }
        });
        getContentPane().add(meetMonster);
        meetMonster.setBounds(849, 323, 281, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatActionPerformed
        // TODO add your handling code here:
        CombatResult c=napakalakiModel.developCombat();
        setNapakalaki(napakalakiModel);
        playerView21.stealNotDiscard();
        if(c!=CombatResult.WIN){
        playerView21.stealDiscard();
        }
        if(c==CombatResult.WINGAME){
            jLabel1.setText("Has ganado");
            combat.setEnabled(false);
            playerView21.stealNotDiscard();
            meetMonster.setEnabled(false);
        }
        if(c!=CombatResult.WINGAME){
        nextTurn.setEnabled(true);
        }
        combat.setEnabled(false);
        
    }//GEN-LAST:event_combatActionPerformed

    private void nextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnActionPerformed
        // TODO add your handling code here:
        
        if(napakalakiModel.nextTurnAllowed()== true){
            napakalakiModel.nextTurn();
        setNapakalaki(napakalakiModel);
        monsterView1.setVisible(false);
        nextTurn.setEnabled(false);
        meetMonster.setEnabled(true);
        playerView21.stealEnabled();
        playerView21.stealMake();
        playerView21.stealDiscard();

        }
        //nextTurn.setEnabled(false);
        //combat.setEnabled(true);
    }//GEN-LAST:event_nextTurnActionPerformed

    private void meetMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetMonsterActionPerformed
        // TODO add your handling code here:
        monsterView1.setVisible(true);
        setNapakalaki(napakalakiModel);
        combat.setEnabled(true);
        meetMonster.setEnabled(false);
        playerView21.stealNotDiscard();

        playerView21.stealNotEnabled();
        playerView21.stealNotMake();
    }//GEN-LAST:event_meetMonsterActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton meetMonster;
    private GUI.MonsterView monsterView1;
    private javax.swing.JButton nextTurn;
    private GUI.PlayerView2 playerView21;
    // End of variables declaration//GEN-END:variables
}
