/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki1.Treasure;

/**
 *
 * @author TOSHIBA
 */
public class TreasureView2 extends javax.swing.JPanel {

    Treasure treasureModel;
    /**
     * Creates new form TreasureView2
     */
    private boolean selected=false;
    public TreasureView2() {
        initComponents();
    }
    public boolean isSelected(){
        return selected;
    }
    public Treasure getTreasure(){
        return treasureModel;
    }
    public void setTreasure(Treasure t){
        treasureModel=t;
        name.setText(treasureModel.getName());
        bonus.setText(Integer.toString(treasureModel.getBonus()));
        tipo.setText(treasureModel.getType().toString());
        setOpaque(false);
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        bonus = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        name.setBackground(new java.awt.Color(153, 153, 153));
        name.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        name.setText("jLabel4");

        bonus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bonus.setForeground(new java.awt.Color(51, 51, 51));
        bonus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bonus.setText("jLabel4");

        tipo.setForeground(new java.awt.Color(51, 51, 51));
        tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipo.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
            .addComponent(tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bonus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bonus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tipo))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if(selected==true){
            setOpaque(false);
            selected=false;
            
        }
        else{
            setOpaque(true);
            selected=true;
            
        }
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonus;
    private javax.swing.JLabel name;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
}
